version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: advertisers-panel-nginx
    restart: on-failure
    volumes:
      - './public/:/usr/src/app:cached'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "8000:80"
    depends_on:
      - php
  php:
    container_name: advertisers-panel-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: on-failure
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_autostart=1
      XDEBUG_KEY: pub
      PHP_IDE_CONFIG: serverName=DOCKER
      TIMEZONE: Europe/Madrid
    volumes:
      - .:/usr/src/app:cached
      - ~/.ssh:/root/.ssh:ro
      - ~/.composer:/root/.composer
  db:
    image: mysql:latest
    container_name: advertisers-panel-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: vidoomy-advertisers-panel
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123123
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  alpine-sqs:
    image: roribio16/alpine-sqs:latest
    container_name: advertisers-panel-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    stdin_open: true
    tty: true
    volumes:
      - ./docker/alpine-sqs:/opt/config:ro
  minio:
    image: minio/minio:latest
    container_name: advertisers-panel-minio
    volumes:
      - ./data:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: development
      MINIO_SECRET_KEY: development-secret
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
