# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'es'
    env(AWS_S3_ENDPOINT): null
    env(AWS_SQS_ENDPOINT): null

    uploads_s3_bucket: '%env(AWS_S3_BUCKET_UPLOADS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    ct_file_store.s3:
        public: true
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
            - version: '%env(AWS_S3_VERSION)%'
              region: '%env(AWS_REGION)%'
              endpoint: '%env(AWS_S3_ENDPOINT)%'
              use_path_style_endpoint: '%env(bool:AWS_S3_USE_PATH_STYLE_ENDPOINT)%'
              credentials:
                  key: '%env(AWS_KEY)%'
                  secret: '%env(AWS_SECRET_KEY)%'

    security.authentication.switchuser_listener:
        class: App\EventListener\SwitchUserListener
        public: false
        abstract: true
        arguments: ["@security.token_storage",
                    "",
                    "",
                    "",
                    "@security.access.decision_manager",
                    "@logger",
                    "_switch_user",
                    "ROLE_ALLOWED_TO_SWITCH",
                    "@event_dispatcher",
                    false]
